### ISSUE TITLE
Functional Widget VS Code Extension

### ISSUE THREAD

**Issue by MassimoTambu** [rrousselGit/functional_widget#102]
Hello,

I was thinking about creating a VS Code extension to refactor **Stateless Widgets** into **Functional Widgets** with some quick action. 
Also I could add extract functionality similar to "Extract Widget" from Flutter extension (obviously I should add another step to choose between @swidget | @hwidget | @hcwidget | @cwidget).

Do you think it could be useful?

**Comment by chientrm** [comment]
Imo just put everything into @hcwidget then no need to care about which widget to use anymore.

**Comment by rrousselGit** [comment]
Sure, feel free to make one. I don't plan on making one myself.

**Comment by avalanche-tm** [comment]
> Hello,
> 
> I was thinking about creating a VS Code extension to refactor **Stateless Widgets** into **Functional Widgets** with some quick action. Also I could add extract functionality similar to "Extract Widget" from Flutter extension (obviously I should add another step to choose between @Swidget | @hwidget | @hcwidget | @cwidget).
> 
> Do you think it could be useful?

Idea is great but I think another issue requires more attention. When you press 'go to definition', you should end up on function instead on class in generated file. I think this is the most painful part of the whole story. I would really like to see that resolved.

**Comment by rrousselGit** [comment]
I'm working on a solution for this already. Don't worry about it.

**Comment by avalanche-tm** [comment]
> I'm working on a solution for this already. Don't worry about it.

Hey, any update on this feature?

**Comment by rrousselGit** [comment]
Yes https://twitter.com/invertaseio/status/1544344104464687107

**Comment by rrousselGit** [comment]
Fixes are already implemented actually


What would code actions be?

**Comment by avalanche-tm** [comment]
> Yes https://twitter.com/invertaseio/status/1544344104464687107

Cool stuff! But I can't see how this helps with functional_widget 'go to definition' issue when you end up in class instead in function. Is it possible to override that behaviour with this package? If so is it going to be included in functional_widget package?

**Comment by rrousselGit** [comment]
custom_lint can change this, yes. Although it needs a PR to the dart analyzer to fix an issue

**Comment by MassimoTambu** [comment]
> Fixes are already implemented actually
> 
> What would code actions be?

[Code actions](https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings) are VS Code options that allows you to fix or refactor something. It's just the term the VS Code documentation uses to classify them.
Existing Dart code actions are implemented directly in the Dart analysis server, but they can also be implemented with analyzer plugins.

Having said that, I saw part of the [video](https://www.youtube.com/watch?v=Okg1Os-gtbo) linked in the repo: as you said they are implemented and it seems that it's quite easy to create an analyzer plugin with dart_custom_lint.

Have you already started creating a plugin for the functional_widget package? If yes, I would be happy to help you out. Otherwise I can get started on something.

**Comment by rrousselGit** [comment]
I haven't started, no

**Comment by MassimoTambu** [comment]
> custom_lint can change this, yes. Although it needs a PR to the dart analyzer to fix an issue

Which PR are you referring to?
