### ISSUE TITLE
Positional optional parameters are not propagated

### ISSUE THREAD

**Issue by westito** [rrousselGit/functional_widget#110]
For named parameters it is solved in this PR:
https://github.com/rrousselGit/functional_widget/pull/45
https://github.com/rrousselGit/functional_widget/issues/44

But positional paramters' default value still not generated

**Comment by rrousselGit** [comment]
Positional optionals don't make sense, as keys are named optionals.

Dart does not support both positional + named optionals.

**Comment by rrousselGit** [comment]
Closing as we cannot support positional optionals since widgets already use named parameters
