### ISSUE TITLE
Difference from Builder?

### ISSUE THREAD

**Issue by gilice** [rrousselGit/functional_widget#112]
**Describe what scenario you think is uncovered by the existing examples/articles**
I don't know why this package is better than just returning a Builder from a function.
It gives access to keys and context too.

```dart
Widget homePage() => Scaffold() // obviously bad, hence this package

@swidget
Widget homePage(BuildContext context) => Scaffold() // better, via this package.

Widget homePage() => Builder((context) => Scaffold()) // what is wrong with this?
```

**Comment by rrousselGit** [comment]
Const constructor, debugFillProperties, devtool integration (you'll just see "Builder" in your case), and slightly improved syntax

**Comment by gslender** [comment]
Figured out another reason to use Builder over this package - you can't use this package in methods, only in top level functions.
