### ISSUE TITLE
Hooks should only be called within the build method of a widget. Error

### ISSUE THREAD

**Issue by DjamelAbbou** [rrousselGit/functional_widget#118]
**Describe the bug**
I wanted to use both functional widgets and hooks to build flutter apps, but as i tried using the useState() hook it gave me the error: Hooks should only be called within the build method of a widget.
Even tho i did add the `@hwidget`.

**To Reproduce**
Just run `flutter create <some_name>` and then paste the following small code:
```
import 'package:flutter/material.dart';
import 'package:functional_widget_annotation/functional_widget_annotation.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

part 'main.g.dart';

@hwidget
Widget homePage() {
  final counter = useState(0);

  return MaterialApp(
      home: SafeArea(
    child: Scaffold(
      body: Center(
        child: ElevatedButton(
            onPressed: () => counter.value++,
            child: Text('Click to increase value: $counter')),
      ),
    ),
  ));
}

void main() {
  runApp(MaterialApp(home: homePage()));
}
```

**Expected behavior**
I expected the code to compile and run.

**Comment by rrousselGit** [comment]
Don't use homePage, use HomePage

**Comment by DjamelAbbou** [comment]
Thank you for answering
I am also using functional_widget package with the hook package, and when i renamed homePage to HomePage, functional_widget package gave out the following error:
`The function name must start with a lowercase character.`
Is there some way to disable this forcing of having to start with a lowercase character?
Or is there a specific way for using both functional_widget and flutter hooks at the same time?

**Comment by rrousselGit** [comment]
>  when i renamed homePage to HomePage, functional_widget package gave out the following error:

Don't rename homePage to HomePage.
functional_widget generated a class named HomePage. Use that
