### ISSUE TITLE
requires SDK version >=2.1.0 <3.0.0, version solving failed on 0.5.0

### ISSUE THREAD

**Issue by felipeaugustox** [rrousselGit/functional_widget#27]
I tried to install the last version, however I get the following error:

> The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
> 
> Because project requires SDK version >=2.1.0 <3.0.0, version solving failed.
> 
> pub get failed (1)
> exit code 1

**Comment by rrousselGit** [comment]
You're using an old version of flutter/dart. Try updating your SDK

**Comment by felipeaugustox** [comment]
> You're using an old version of flutter/dart. Try updating your SDK

I see, didn't know `-` meaning is pre-release version.
