### ISSUE TITLE
Bump analyzer needed to mobX compatibility 

### ISSUE THREAD

**Issue by jaumard** [rrousselGit/functional_widget#30]
```
Because mobx_codegen >=0.0.7 depends on analyzer ^0.35.0 and functional_widget 0.5.0 depends on analyzer >=0.32.2 <0.34.0, mobx_codegen >=0.0.7 is incompatible with functional_widget 0.5.0.
And because no versions of functional_widget match >0.5.0 <0.6.0, mobx_codegen >=0.0.7 is incompatible with functional_widget ^0.5.0.
```

**Comment by twistedinferno** [comment]
Hi Remi, is this on your radar at all, I have a similar package conflict with analyzer (I'm finally back using flutter again!)

**Comment by rrousselGit** [comment]
You can submit a PR of you want to.
I'm currently a bit tired to be honest

**Comment by twistedinferno** [comment]
:+1:  no problem, I should have time tomorrow.  (a walk in the countryside is a good refresh, btw, many thanks for your talk in London)

**Comment by twistedinferno** [comment]
Apologies for the delay, I just tried to do this now.  I cloned the repository locally, made the changes, created a new branch locally, when publishing the branch I get
Git: Permission to rrousselGit/functional_widget.git denied to twistedinferno.
Is this the right approach, is it as simple as requiring permission?
Cheers

**Comment by rrousselGit** [comment]
You must fork the project instead then make a pull request

**Comment by twistedinferno** [comment]
ok!

**Comment by twistedinferno** [comment]
done, btw I have my project referenced to a path version of this project so I can continue now without re-publishing the package

**Comment by twistedinferno** [comment]
Hi Remi, I thought I had it working yesterday but I think I didn't properly pull both functional_widget and my dart package that uses another version of analyzer into the project.  I'm getting the following message in my flutter project that references both `functional_widget` and another project that uses an updated version of analyzer.  I'm not getting any compile issues and I can't see where any of the classes below are referenced in the functional_widget code.  Any ideas off the top of your head?  There is a resolveCompilationUnit function but it has a different signature to both the signatures specified below.
```
Error running FunctionalWidgetGenerator
NoSuchMethodError: Class 'RestrictedAnalysisContext' has no instance method 'resolveCompilationUnit' with matching arguments.
Receiver: Instance of 'RestrictedAnalysisContext'
Tried calling: resolveCompilationUnit(Instance of 'FileSource', Instance of 'LibraryElementImpl')
Found: resolveCompilationUnit(Source, LibraryElement) => CompilationUnit
```

**Comment by twistedinferno** [comment]
Hi Remi @rrousselGit, second attempt and thanks to help from natebosch it compiles my code too so I can continue with this local version and be happy.  There is a problem with the CI build that I couldn't understand so the pull request checks have failed.  If you can spot anything and want me to make a change let me know.  Cheers

**Comment by rrousselGit** [comment]
Sure, I'll take a look as soon as I can :)

**Comment by rrousselGit** [comment]
The pull request issue is that there's a file (findBeginToken.dart) that isn't correctly formated

**Comment by twistedinferno** [comment]
it seems ok in vs code, I haven't used travis ci before and couldn't find the failure message.  I've done alt + shft + f vs code and the file is the same.  Can you see what the formatting problem is?  findBeginToken.dart contains a single function that does the same as the deprecated computeNode

**Comment by twistedinferno** [comment]
There was no new line after the function body, I doubt that was the problem but I've just pushed again just in case

**Comment by twistedinferno** [comment]
ha, it was that!

**Comment by rrousselGit** [comment]
Should be good to go.

**Comment by NarHakobyan** [comment]
have you merged it?

**Comment by rrousselGit** [comment]
Yes
