### ISSUE TITLE
Error with @required arguments with not included types

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/functional_widget#31]
When using a parameter both `@required` and with a type not included in the Dart SDK (`Color` for example), the generation fails.

Example :
```
@widget 
Widget example(BuildContext context, {@required Color splashColor}) 
```

Produces :
```
line 17, column 7: Expected an identifier.
   ╷
17 │ final @ splashColor;
   │       ^
   ╵
line 17, column 7: Expected to find ';'.
   ╷
17 │ final @ splashColor;
   │       ^
   ╵
line 17, column 20: Expected a class member.
   ╷
17 │ final @ splashColor;
   │                    ^
```

This is due of the access of the first token of the `computedNode`.

**Comment by rrousselGit** [comment]
I can't do much about it. It's the à blocker on the generator side

**Comment by aloisdeniel** [comment]
You may can check what is the first token in the sequence... but since computedNode is deprecated it is not a long term solution infortunately.

**Comment by rrousselGit** [comment]
That `computeNode` usage do not aim at being a long-term solution, so I'm fine with a deprecated function that barely fixes the problem.

It just handles the most common usage.

**Comment by aloisdeniel** [comment]
A potential solution could be to check if the node is an [AnnotatedNode](https://pub.dartlang.org/documentation/analyzer/0.30.0+3/analyzer.dart.ast.ast/AnnotatedNode-class.html) and if so use `visitChildren` to get the declared identifier.

**Comment by rrousselGit** [comment]
How so? We're using `computeNode` when the analyzer is unable to resolve nodes.

**Comment by aloisdeniel** [comment]
Hum, only when the **element's type** is undefined, not the element itself.

```dart
Reference _parameterToReference(ParameterElement element) {
  if (element.type.isUndefined) {
    return refer(element.computeNode().beginToken.toString());
  }
```

We may here try to get the annotation associated with `element` before accessing its first token.

I will try some experiments as soon as I get the time to.

**Comment by rrousselGit** [comment]
Closing this, since I cannot do anything. 

As a workaround you may use a custom object:


```dart
class MyColor {
  MyColor(this.color);
  final Color color;
}
```


and send it to the generator:

```dart
@widget Widget foo({@required MyColor color}) {}
```


This will correctly build.
