### ISSUE TITLE
Support for class functions

### ISSUE THREAD

**Issue by tvhnet2014** [rrousselGit/functional_widget#33]
My idea is to make functional_widget support for functions inside class as well as class inheritance and function overriding.
```
class A extends StatelessWidget
{
     @override
     Widget build(BuildContext context) => test();

     @widget
     Widget test() => Container()
}

class B extends A
{
     @widget
     @override
     Widget test() => Text("hello");
}
```

**Comment by rrousselGit** [comment]
What is the expected behavior in that situation?

I don't understand what should be generated.

**Comment by rrousselGit** [comment]
In the absence of an answer, I'll close this for now. Feel free to reopen if you can provide further information on the desired behavior.
