### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NourEldinShobier** [rrousselGit/functional_widget#37]
Is it possible to use interfaces with fucntional widgets ?

**Comment by rrousselGit** [comment]
Hello!

Can you clarify? I don't understand how that would work.

**Comment by NourEldinShobier** [comment]
I'm really sorry, i meant interfaces
example:
```
class CustomAppBar extends StatelessWidget implements PreferredSizeWidget{
}
```

**Comment by rrousselGit** [comment]
That's not possible no. A single function is not enough to handle such complex use-case.

**Comment by NourEldinShobier** [comment]
Thanks a lot.
