### ISSUE TITLE
Builder vs Build_runner

### ISSUE THREAD

**Issue by slyedoc** [rrousselGit/functional_widget#40]
I am returning to flutter and I am looking to uses the "builders" option in pubspec.yaml instead of build_runner.  In the readme, it says that method should work unless you're using an older version of flutter.  Have tried lastest stable, dev, and master (1.8.2) but as far as I can tell nothing uses this option and I can't find any documentation on this option after an hour of searching.  Going to back to build_runner, but would like to use it for future use.  Am I just missing something?

**Comment by rrousselGit** [comment]
See https://github.com/rrousselGit/functional_widget/blob/master/functional_widget/example/pubspec.yaml

You can generate the sources using `flutter generate`, which is run automatically on `flutter run` and `flutter build`.

**Comment by cubuspl42** [comment]
@rrousselGit I couldn't find any documentation on the "builders" key in the Dart/Flutter documentation. I had no luck with `flutter generate`, either. Is this an experimental feature without any stability guarantees? How did you learn about it?

**Comment by cubuspl42** [comment]
There is hardly any or no documentation for these features ("builders" / `flutter generate`. Are they considered stable?
I found this: https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter

**Comment by rrousselGit** [comment]
`build.yaml` is another secondary file (which is optional and mentioned in this README here https://github.com/rrousselGit/functional_widget#customize-the-output).

**Comment by rrousselGit** [comment]
They are stable (since they are literally on the `stable` channel).
But yeah, they aren't very well documented.

**Comment by cubuspl42** [comment]
https://github.com/flutter/flutter/issues/43176
