### ISSUE TITLE
Support hiding the "raw" functions

### ISSUE THREAD

**Issue by derolf** [rrousselGit/functional_widget#42]
It would be nice to decorate _example and generate Example so that users don't refer to _example by accident.

**Comment by rrousselGit** [comment]
You mean to write a private function and it'd generate a public class?

**Comment by derolf** [comment]
Exactly.

**Comment by rrousselGit** [comment]
It's an interesting idea. But then, how would peoples generate private classes?

**Comment by derolf** [comment]
With two underscores 😂

Von meinem iPhone gesendet

**Comment by derolf** [comment]
What about making it an option you can pass? (Remove leading underscore)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rrousselGit** [comment]
The generated class name is now the function name, with the first `_` removed

So:
- fn => Fn
- _fn => Fn
- __fn => _Fn


This should cover this use-case
