### ISSUE TITLE
VoidCallback parameter yields dynamic

### ISSUE THREAD

**Issue by derolf** [rrousselGit/functional_widget#43]
Example:

```
@widget
Widget foo(VoidCallback bar) => Container();
```

generates

```
class Foo extends StatelessWidget {
  const Foo(this.bar, {Key key}) : super(key: key);

  final dynamic bar;

  @override
  Widget build(BuildContext _context) => foo(bar);
}
```

resulting in error:

```
The argument type 'dynamic' can't be assigned to the parameter type 'VoidCallbackvoid Function()'.dart(argument_type_not_assignable)
```

**Comment by rrousselGit** [comment]
The issue is on https://github.com/dart-lang/build/issues/733. `functional_widget` cannot do anything about it, sadly.

**Comment by derolf** [comment]
I don't get what the actual problem is... because it works for other types...

However, a workaround is to declare `VoidCallback` in the same (original) file.

**Comment by rrousselGit** [comment]
The issue is, voidcallback is originally defined in Flutter. Which code generators don't have access to.
So the type do not resolve

**Comment by derolf** [comment]
Got it! Probably you should mention that in the docs...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by derolf** [comment]
Could this workaround work here as well? https://github.com/spkersten/dart_functional_data/issues/3#issuecomment-520272470

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by derolf** [comment]
I am not able to replicate this issue in a test. Do you know how to do that?

**Comment by rrousselGit** [comment]
Wait, Voidcallback? The issue should happen for things from dart:ui only, like Color.

Voidcallback should work (although the generator will instead write `void Function()`

**Comment by derolf** [comment]
I have a fix. Should work now.

**Comment by cubuspl42** [comment]
Any progress on this one? It's a blocker for me...

**Comment by rrousselGit** [comment]
No. You can make a PR if you need to.

**Comment by liri2006** [comment]
I'm getting same issue for basically any custom type defined outside of file with widget.

**Comment by derolf** [comment]
You might want to revamp https://github.com/rrousselGit/functional_widget/pull/48

**Comment by liri2006** [comment]
@rrousselGit Can you take a look at PR @derolf submitted when you have a minute? This lib is awesome and it would be great to get this issue fixed.

**Comment by truongsinh** [comment]
with the latest version, i can no longer recreate this bug.

```dart
@widget
Widget foo(VoidCallback bar) => Container();
```
generates for me (excuse `HookWidget` but it should be the same anyway)
```dart
class Foo extends HookWidget {
  const Foo(this.bar, {Key key}) : super(key: key);

  final void Function() bar;

  @override
  Widget build(BuildContext _context) => foo(bar);
}
```

**Comment by rrousselGit** [comment]
Good catch
