### ISSUE TITLE
For discussion: Lists and hashCode/operator==

### ISSUE THREAD

**Issue by derolf** [rrousselGit/functional_widget#47]
In Dart, `List`s don't do deep hashCode or operator==, i.e. `['a'].hashCode != ['a'].hashCode` and `['a'] != ['a']`.

Should `functional_widget` detect Lists and provide deep hashCode/==?

**Comment by rrousselGit** [comment]
No, probably not.
It's up to the list owner to implement such a feature – especially considering it can be costly depending on the list size.

**Comment by rrousselGit** [comment]
There are a few packages that offer classes with implements `List` with a custom hashCode/==, like https://github.com/passsy/kt.dart
