### ISSUE TITLE
Code not generated when using builder

### ISSUE THREAD

**Issue by PiN73** [rrousselGit/functional_widget#56]
According to [Install (builder) in readme](https://github.com/rrousselGit/functional_widget/blob/2ca3c7e6d83b97691b0c9f35518c8b1db44c9071/README.md#install-builder), I added dependencies in pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.5.1

builders:
  functional_widget: ^0.7.1
```

and made a simple widget
```dart
@widget
Widget foo(BuildContext context, int value) {
  return Text('$value');
}
```

However when I add `Foo(42)` in my code and try to run it, it doesn't work
```
Compiler message:
org-dartlang-app:/main.dart:23:16: Error: Method not found: 'Foo'.
        child: Foo(42),
               ^^^
org-dartlang-app:/main.dart:23:16: Error: The method 'Foo' isn't defined for the class 'MyHomePage'.
 - 'MyHomePage' is from 'package:test_functional_widget/main.dart' ('org-dartlang-app:/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Foo'.
        child: Foo(42),
               ^^^
```

[`flutter build apk` log](https://gist.github.com/PiN73/ffe65a71cc7a75a15160e0c2f319365e)
[`flutter run` log](https://gist.github.com/PiN73/ad210b3f9477c96b0b5a84e6702c47b8)
[`flutter doctor`](https://gist.github.com/PiN73/47c06cdfe1a9e764c1df68f4fb99d99a)

[Repository](https://github.com/PiN73/test_functional_widget) with my example app

**Comment by rrousselGit** [comment]
You are missing the `part 'foo.g.dart';`  on the top of your file

**Comment by PiN73** [comment]
Thanks, adding `part 'foo.g.dart';` solved the problem. I think it's worth adding to readme. Here is a pull request #57
