### ISSUE TITLE
Use `Dill` to eliminate the need of generated code?

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/functional_widget#59]
We know that we can use kernel-to-kernel transformation to change the `dill` (dart intermediate language). There is already some libraries, such as https://github.com/alibaba-flutter/aspectd, which uses this to modify the code during compilation. Therefore, I think we can do the same thing to transform the `functional_widget`s. :)

P.S. [This article](https://mp.weixin.qq.com/s?__biz=MzU4MDUxOTI5NA==&mid=2247484555&idx=1&sn=b0551bcdbbbfb8a5f1a52ca227435984) explains this technique, but it is only in Chinese...

**Comment by rrousselGit** [comment]
I'm not familiar with it (nor do I understand Chinese)

Do you mind expanding a bit more on how that would work?

**Comment by fzyzcjy** [comment]
It is a bit like *macros* in other languages, and I will try to explain more when having time.
