### ISSUE TITLE
Support [assert(...)]of some parameters

### ISSUE THREAD

**Issue by pedromassango** [rrousselGit/functional_widget#65]
Does declaring a widget as a function support parameters's assert?

Most of the times I writ my code as:

```dart
class MyWidget extends StatelessWidget {
  final int valueA;
  final int valueB;
  
  MyWidget({this.valueA, this.valueB})
    : assert(valueA != null),
      assert(valueB != 1);
  
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

How do I write the assert so that this package can apply in the generated widget?
If I write it in the fuction it will be moved in the generated widget as well?

**Comment by rrousselGit** [comment]
It is really needed?
The assert can be placed directly inside the function:

```dart
@swidget
Widget example(int value) {
  assert(value > 0);
  return Container();
}
```

**Comment by pedromassango** [comment]
My doubt is if the assert will be called since we will use the generated widget istead of the function. Yes it is needed sometimes I need to put some restrictions in the provided parameters.

**Comment by rrousselGit** [comment]
The generated widget calls your function, so asserts will be called correctly

**Comment by rrousselGit** [comment]
Closing since I believe supporting asserts on the constructor when we can place asserts inside the function has a low benefit

I'm open to pull-requests though
