### ISSUE TITLE
Add option to customize name

### ISSUE THREAD

**Issue by mhmdanas** [rrousselGit/functional_widget#70]
Maybe something like this:
```dart
@FunctionalWidget(className: 'FooBar')
Widget foo() => Text('foo');
```

**Comment by rrousselGit** [comment]
Hi!

What's the use-case? 😄

**Comment by mhmdanas** [comment]
I mainly would like this feature for acronyms at the beginning of the widget's name.

**Comment by rrousselGit** [comment]
I don't understand

Do you have an example?

**Comment by mhmdanas** [comment]
Here's an example:
```dart
Widget ioWidget() => // Whatever;
```

This generates a widget with the name `IoWidget`. I would want the widget to have the name `IOWidget`. It _is_ possible to use `iOWidget` as the function name, but it looks ugly.

**Comment by mhmdanas** [comment]
Also, I think this would fix #42 because one can use a public widget name for a private function, but I don't like this because one will have to sync the widget name and the class name.

**Comment by rrousselGit** [comment]
I see

Feel free to make a pull request 😄

**Comment by mhmdanas** [comment]
I'll see if I can do it!

**Comment by mhmdanas** [comment]
I took a stab at this and I wasn't able to do it unfortunately, and I'm a little busy. If anybody would like to fix this issue, go ahead!

**Comment by mhmdanas** [comment]
In retrospect, this doesn't look that necessary to me anymore. I _did_ say that
> It is possible to use `iOWidget` as the function name, but it looks ugly.

but honestly, that doesn't seem like a strong enough reason to add this.
