### ISSUE TITLE
Adding functional_widget_annotation import caused calls in Stateful widget to have errors

### ISSUE THREAD

**Issue by MostHated** [rrousselGit/functional_widget#71]
I am not exactly sure if it's related to #70 but as soon as I added ```import 'package:functional_widget_annotation/functional_widget_annotation.dart';``` in a stateful widget, my calls from the private class to wiget.whatEverHere threw errors throughout the entirety of the class, so I could not do anything at that point and had to remove it before I had the opportunity to test it out.

Is there a restriction of wigets having to originate in a stateless class and I just missed the note on it? I read through the readme and don't recall seeing it.

Thanks,
-MH

**Comment by rrousselGit** [comment]
This happens because there's an annotation called "widget" which surprisingly happens to override State.widget

To fix:

```
import 'package:functional_widget_annotation/functional_widget_annotation.dart' hide widget;
```

**Comment by rrousselGit** [comment]
`@widget` was removed in 0.8.0
