### ISSUE TITLE
Name of generated widget

### ISSUE THREAD

**Issue by subzero911** [rrousselGit/functional_widget#75]
How about adding the name attribute?
`@swidget(name: 'MyCoolWidget')`

Also maybe add a configurable naming rule into `build.yaml`?
I thought about it, because builder methods are most often named like: `_buildHeader()`, `_buildDataList()`
But I want to have resulting widgets like `Header()` instead of `_BuildHeader()`

**Comment by rrousselGit** [comment]
Duplicate of #70
