### ISSUE TITLE
Allow SingleChildStatelessWidget generation (@nwidget)

### ISSUE THREAD

**Issue by PavelPZ** [rrousselGit/functional_widget#76]
I like both **functional_widget** and **nested** packages:

```
@nwidget
Widget w1() => child; 

@nwidget
Widget w2() => child;

@swidget
Widget wBoth() => Nested(
  children: [
    W1(),
    W2(),
  ],
  child: Text('Great!'),
)

```

**Comment by rrousselGit** [comment]
I don't mind, but what is the use-case?

**Comment by rrousselGit** [comment]
Nested widgets are not very performant so it really depends on what you want to do with them.

If your goal is you make UI elements (which is the primary use-case of functional_widget), `nested` is a bad idea.

**Comment by PavelPZ** [comment]
performance is important, closing...
