### ISSUE TITLE
latest build_runner not working

### ISSUE THREAD

**Issue by Adidi** [rrousselGit/functional_widget#77]
When i try to install the packages i get this:
![image](https://user-images.githubusercontent.com/1063328/97166519-0d3f9e00-178e-11eb-9db7-cd0dd79e3ad5.png)

Is there any plan soon to upgrade `analyzer` i see it on version ` ^0.39.8` on functional_widget pubspec.yaml 

Thanks

**Comment by karianpour** [comment]
Any answer? @Adidi did you find a work around?

**Comment by Adidi** [comment]
@karianpour  `build_runner: ^1.10.2` version is working.
its only the latest - I guess its not that crucial and I am sure  @rrousselGit will update dependencies soon

**Comment by rrousselGit** [comment]
Sorry for the delay

This should be fixed in 0.8.1
