### ISSUE TITLE
Is it possible to jump to the functional widget declaration instead of the generated widget when ctrl+clicking the generated widget?

### ISSUE THREAD

**Issue by harkairt** [rrousselGit/functional_widget#81]
I like this lib, but the code navigation is considerably hindered, for which I haven't found a documented solution.
Lets say I have a widget
```
@swidget
Widget myWidget() => Text('hello');
```
which is somewhere used as `MyWidget`. If I want to jump to this widget with ctrl+click the IDE navigates to the generated file, which makes sense obviously, but still unwanted in this scenario. 

Thanks

**Comment by rrousselGit** [comment]
Sadly not at the moment

**Comment by rrousselGit** [comment]
Closing since there's nothing I can do here
