### ISSUE TITLE
"BuildContext context" issue if not first param

### ISSUE THREAD

**Issue by salvaterra** [rrousselGit/functional_widget#83]
Generated code creates a new variable if "BuildContext context" is not the 1st parameter, but instead 2nd or 3rd etc. I assume this is not expected, if so we should maybe document it.

**Comment by rrousselGit** [comment]
This is expected

functional_widget injects the context only to the first _positional_ param

See https://github.com/rrousselGit/functional_widget#all-the-potential-function-prototypes

**Comment by salvaterra** [comment]
Got it, thank you, my bad. Maybe as a suggestion reword this sentence a bit "You can then add however many arguments you like after the previously defined arguments."
