### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Michael35699** [rrousselGit/functional_widget#84]
Would this generator support null safety soon?

**Comment by rrousselGit** [comment]
It's not in my priority list.

You can raise a PR if you need it soon

**Comment by tim-smart** [comment]
I have started working on something here: https://github.com/tim-smart/functional_widget/tree/null-safety

Got it working for one of my projects, but might need a bit more polish (and some more tests).

**Comment by rrousselGit** [comment]
Thanks! Feel free to open a PR. I'll gladly review it

**Comment by rrousselGit** [comment]
Released as part of 0.9.0
