### ISSUE TITLE
Reasoning behind equality generation deletion

### ISSUE THREAD

**Issue by liri2006** [rrousselGit/functional_widget#90]
I'm curious, why functional_widget no longer generates the equal operation overloads (that was, in my opinion, a quite a neat benefit to usage of swidget)?

**Comment by rrousselGit** [comment]
This behavior was deprecated. Overriding == on widgets is now disrecommended

**Comment by liri2006** [comment]
@rrousselGit Thanks, but do you maybe know why?

**Comment by rrousselGit** [comment]
Because the performance benefits aren't so clear

And it's easy to end-up with an inefficient == and end-up comparing the entire widget tree.
