### ISSUE TITLE
Can't currently have `functional_widget` and `freezed` both installed at the same time

### ISSUE THREAD

**Issue by mhmdanas** [rrousselGit/functional_widget#93]
**Describe the bug**
I can't have the latest version of `functional_widget` and `freezed` installed at the same time.

**To Reproduce**

Just try to have both `functional_widget: 0.9.0+2` and `freezed: 0.14.3` installed at the same time.

**Expected behavior**
I expect it to work.

**Actual behavior**
```console
$ flutter pub get
Because functional_widget >=0.9.0 depends on analyzer ^1.1.0 and freezed >=0.14.3 depends on analyzer ^2.0.0, functional_widget >=0.9.0 is incompatible with freezed >=0.14.3.
So, because foo depends on both freezed 0.14.3 and functional_widget 0.9.0+2, version solving failed.
Running "flutter pub get" in foo...
pub get failed (1; So, because foo depends on both freezed 0.14.3 and functional_widget 0.9.0+2, version solving
failed.)
```

**Workarounds**
Using `freezed: 0.14.2` works.

**Note**: I reported this here because `functional_widget` is the one which depends on an outdated `analyzer`. Feel free to transfer to `freezed` if appropriate.

**Comment by adrianjagielak** [comment]
You can add dependency overrides to your `pubspec.yaml` like that:

```yaml
dependency_overrides:
  analyzer: ^2.1.0
```

**Comment by rrousselGit** [comment]
This was apparently fixed but not closed, so I'll close it
